{
 "title": "Netdata: Apps Stats",
 "description": "Per application overview (CPU/RAM/Disk/etc)",
 "tags": [
  "system",
  "apps"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "interval", "query": "15s,1m,5m,1h,6h,1d" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(netdata_apps_processes{job=~\".+\"},job)"
    }
   },
   {
    "name": "env",
    "label": "Environment",
    "query": {
     "query": "label_values(netdata_apps_processes{env=~\".+\"},env)"
    }
   },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(netdata_apps_processes{env=\"$env\"},instance)"
    }
   },
   {
    "name": "source",
    "label": "Source",
    "query": {
     "query": "label_values(netdata_apps_processes{env=\"$env\",instance=~\"$host\"},source)"
    }
   },
   {
    "name": "app",
    "label": "Application",
    "query": {
     "query": "label_values(netdata_apps_processes{env=\"$env\",instance=~\"$host\"},dimension)"
    }
   },
   { "name": "limit", "label": "Limit", "query": "3,5,10,15,20,30,50" }
  ]
 },
 "panels": [
  {
   "title": "CPU User ($app)",
   "type": "graph",
   "description": "Apps CPU Time (NNN% = N cores) (apps.cpu_user)",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "topk($limit,sum(netdata_apps_cpu_user{job=\"$job\", env=~\"$env\",dimension=~\"$app\",instance=~\"$host\",source=~\"$source\"}) by (dimension)) / 10000",
     "legendFormat": "{{dimension}}"
    }
   ]
  },
  {
   "title": "CPU System ($app)",
   "type": "graph",
   "description": "Apps CPU Time (NNN% = N cores) (apps.cpu_system)",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "topk($limit,sum(netdata_apps_cpu_system{job=\"$job\", env=~\"$env\",dimension=~\"$app\",instance=~\"$host\",source=~\"$source\"}) by (dimension)) / 10000",
     "legendFormat": "{{dimension}}"
    }
   ]
  },
  {
   "title": "Memory Usage ($app)",
   "type": "graph",
   "description": "Real memory (RAM) used by applications. This does not include shared memory.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "topk($limit,sum(netdata_apps_mem{job=\"$job\", env=~\"$env\",dimension=~\"$app\",instance=~\"$host\",source=~\"$source\"}) by (dimension))",
     "legendFormat": "{{dimension}}"
    }
   ]
  },
  {
   "title": "Virtual Memory Usage ($app)",
   "type": "graph",
   "description": "Virtual memory allocated by applications.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "topk($limit,sum(netdata_apps_vmem{job=\"$job\", env=~\"$env\",dimension=~\"$app\",instance=~\"$host\",source=~\"$source\"}) by (dimension))",
     "legendFormat": "{{dimension}}"
    }
   ]
  },
  {
   "title": "Disk reads ($app)",
   "type": "graph",
   "description": "Apps Disk Reads (apps.preads)",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "topk($limit,sum(netdata_apps_preads{job=\"$job\", env=~\"$env\",dimension=~\"$app\",instance=~\"$host\",source=~\"$source\"}) by (dimension)) / 10240000",
     "legendFormat": "{{dimension}}"
    }
   ]
  },
  {
   "title": "Disk writes ($app)",
   "type": "graph",
   "description": "Apps Disk Writes (apps.pwrites)",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "topk($limit,sum(netdata_apps_pwrites{job=\"$job\", env=~\"$env\",dimension=~\"$app\",instance=~\"$host\",source=~\"$source\"}) by (dimension)) / 10240000",
     "legendFormat": "{{dimension}}"
    }
   ]
  },
  {
   "title": "Swap Usage ($app)",
   "type": "graph",
   "description": "Swapped memory by applications.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "topk($limit,sum(netdata_apps_swap{job=\"$job\", env=~\"$env\",dimension=~\"$app\",instance=~\"$host\",source=~\"$source\"}) by (dimension))",
     "legendFormat": "{{dimension}}"
    }
   ]
  },
  {
   "title": "Threads ($app)",
   "type": "graph",
   "description": "Apps Threads (apps.threads)",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk($limit,sum(netdata_apps_threads{job=\"$job\", env=~\"$env\",dimension=~\"$app\",instance=~\"$host\",source=~\"$source\"}) by (dimension))",
     "legendFormat": "{{dimension}}"
    }
   ]
  },
  {
   "title": "Processes ($app)",
   "type": "graph",
   "description": "Apps Processes (apps.processes)",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk($limit,sum(netdata_apps_processes{job=\"$job\", env=~\"$env\",dimension=~\"$app\",instance=~\"$host\",source=~\"$source\"}) by (dimension))",
     "legendFormat": "{{dimension}}"
    }
   ]
  },
  {
   "title": "Open sockets ($app)",
   "type": "graph",
   "description": "Apps Open Sockets (apps.sockets)",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk($limit,sum(netdata_apps_sockets{job=\"$job\", env=~\"$env\",dimension=~\"$app\",instance=~\"$host\",source=~\"$source\"}) by (dimension))",
     "legendFormat": "{{dimension}}"
    }
   ]
  },
  {
   "title": "Local disk reads ($app)",
   "type": "graph",
   "description": "Apps Disk Logical Reads (apps.lreads)",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "topk($limit,sum(netdata_apps_lreads{job=\"$job\", env=~\"$env\",dimension=~\"$app\",instance=~\"$host\",source=~\"$source\"}) by (dimension)) / 10240000",
     "legendFormat": "{{dimension}}"
    }
   ]
  },
  {
   "title": "Local disk writes ($app)",
   "type": "graph",
   "description": "Apps I/O Logical Writes (apps.lwrites)",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "topk($limit,sum(netdata_apps_lwrites{job=\"$job\", env=~\"$env\",dimension=~\"$app\",instance=~\"$host\",source=~\"$source\"}) by (dimension)) / 10240000",
     "legendFormat": "{{dimension}}"
    }
   ]
  },
  {
   "title": "Open files ($app)",
   "type": "graph",
   "description": "Apps Files (apps.files)",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk($limit,sum(netdata_apps_files{job=\"$job\", env=~\"$env\",dimension=~\"$app\",instance=~\"$host\",source=~\"$source\"}) by (dimension))",
     "legendFormat": "{{dimension}}"
    }
   ]
  },
  {
   "title": "More graphs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "panels": [
    {
     "title": "Open pipes ($app)",
     "type": "graph",
     "description": "Apps Pipes (apps.pipes)",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk($limit,sum(netdata_apps_pipes{job=\"$job\", env=~\"$env\",dimension=~\"$app\",instance=~\"$host\",source=~\"$source\"}) by (dimension))",
       "legendFormat": "{{dimension}}"
      }
     ]
    },
    {
     "title": "Major Page Fault / Swap Read ($app)",
     "type": "graph",
     "description": "A page fault is a type of interrupt, called trap, raised by computer hardware when a running program accesses a memory page that is mapped into the virtual address space, but not actually loaded into main memory. If the page is loaded in memory at the time the fault is generated, but is not marked in the memory management unit as being loaded in memory, then it is called a minor or soft page fault. A major page fault is generated when the system needs to load the memory page from disk or swap memory.",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 48 },
     "yaxes": [
      { "format": "deckbytes" }
     ],
     "targets": [
      {
       "expr": "topk($limit,sum(netdata_apps_major_faults{job=\"$job\", env=~\"$env\",dimension=~\"$app\",instance=~\"$host\",source=~\"$source\"}) by (dimension))",
       "legendFormat": "{{dimension}}"
      }
     ]
    },
    {
     "title": "Minor Page Fault / Memory Read ($app)",
     "type": "graph",
     "description": "A page fault is a type of interrupt, called trap, raised by computer hardware when a running program accesses a memory page that is mapped into the virtual address space, but not actually loaded into main memory. If the page is loaded in memory at the time the fault is generated, but is not marked in the memory management unit as being loaded in memory, then it is called a minor or soft page fault. A major page fault is generated when the system needs to load the memory page from disk or swap memory.",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 53 },
     "yaxes": [
      { "format": "deckbytes" }
     ],
     "targets": [
      {
       "expr": "topk($limit,sum(netdata_apps_minor_faults{job=\"$job\", env=~\"$env\",dimension=~\"$app\",instance=~\"$host\",source=~\"$source\"}) by (dimension))",
       "legendFormat": "{{dimension}}"
      }
     ]
    }
   ]
  }
 ]
}